### ISSUE TITLE
How to generate configure.ac and Makefile.am from SVN?

### ISSUE THREAD

**Issue by GoogleCodeExporter** [armando-basile/comex-project#1]
```
The comex-base-0.1.8.5.tar.gz archive contains a ./configure script

Howto generate this script from the SVN source code version? Is it generated by 
monodevelop?

I need the steps to go from SVN checkout and then use the "Build and install 
from tarballs" procedure.

The installation process in "Build from sources" is (too) complex (for me) and 
should be automated.
```

Original issue reported on code.google.com by `ludovic....@gmail.com` on 22 Oct 2011 at 9:18

**Comment by armando-basile** [comment]
generation of makefile from monodevelop is an abandoned project, see [mdtool-generation-of-makefile](http://stackoverflow.com/questions/13036587/mdtool-generation-of-makefile), right approach is cross build tool **xbuild** / **msbuild** (monodevelop is no longer required, only mono).

now also comex-base isn't an external dependency, but is compiled and copied with gui project
