### ISSUE TITLE
Build failure on Mageia Cauldron with latest 0.1.9 version against log4net 1.2.15

### ISSUE THREAD

**Issue by david-geiger** [armando-basile/comex-project#3]
Hi,

Since latest log4net release 1.2.15 comex doesn't built anymore, we get an error on compile:

http://pkgsubmit.mageia.org/autobuild/cauldron/x86_64/core/2016-03-28/comex-0.1.9-3.mga6.src.rpm/build.0.20160328001124.log

Regards,
David

**Comment by armando-basile** [comment]
i'm going to reproduce build error into a cauldron vm. Using Mageia 5 with a rebuilded log4net 1.2.15 package there aren't build problems, so could be a Mono runtime release problem.

**Comment by david-geiger** [comment]
Ah :(   and we have this same build error for themonospot and probably for monosim.

http://pkgsubmit.mageia.org/autobuild/cauldron/x86_64/core/2016-03-28/themonospot-0.9.0-2.mga6.src.rpm/build.0.20160328001124.log

**Comment by armando-basile** [comment]
from mono 4, target framework .Net 2.0, 3.0, 3.5 and 4.0 was dropped see [mono 4.0.0 Release Notes](http://www.mono-project.com/docs/about-mono/releases/4.0.0/#dropped-support-for-old-frameworks) so i only need to reset target framework for all projects to 4.5

**Comment by armando-basile** [comment]
Now [build log](http://pkgsubmit.mageia.org/uploads/done/cauldron/core/release/20160404205937.hman.duvel.1497/comex-0.1.9-6.mga6/build.0.20160404210005.log) seems to be ok :)

**Comment by david-geiger** [comment]
Yeah!! good!! excellent

Thank you :)

So now still for themonospot and monosim :)

**Comment by armando-basile** [comment]
done

**Comment by david-geiger** [comment]
Thanks a lot Armando! all are fixed now.

I did not know that you were 'hman' on Mageia :)
